ACON3D/ABLER

release/scripts/startup/abler/layer_control.py

괄호 위치때문에 layer 패널에서 오류가 나는 부분 수정했습니다!

change ")" location

---

release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py

tracking import button

---

release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/lib/tracker/_tracker.py

한번 트래킹을 하고나서 중복되는 트래킹은 무시하는 데코레이터를 추가함으로써 다중 Look at me 트래킹을 구현했습니다.
또한 Look at me를 켜줄때만 트래킹을 하기위해 조건문을 달아주었습니다.

tracking Look At Me button

---

release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/scene_control.py

scene 추가 버튼 tracker를 만들었습니다.
"Add Scene"으로 하려다가 Scene관련한 내용들을 한꺼번에 보면 좋을거 같아서 "Scene Add"로 정의했습니다!

tracking scene add button

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py

toggle toolbar 버튼 tracker 만들었습니당

tracking toggle toolbar button

---

release/scripts/startup/abler/camera_control.py

ACON_col_cameras 컬렉션이 없을 때 패널에서 카메라 기능이 표시되지 않는 버그를 개선합니다.

Fix camera control panel bug

---

.gitignore
abler_requirements.txt
build_files/windows/check_libraries.cmd
build_files/windows/find_dependencies.cmd
release/scripts/startup/abler/lib/tracker/__init__.py
release/scripts/startup/abler/lib/tracker/_mixpanel.py
release/scripts/startup/abler/lib/tracker/_sentry.py

기존에 각기 다른 토큰 파일로 관리되던 녀석을 dotenv로 관리할 수 있도록 수정하고, dotenv 파이썬 설치까지 추가했습니다. 
- windows에서 파이썬 requirements가 제대로 등록이 안되는 현상이 있어서 수정했습니다.
- 중간중간 의미없는 f-string이 있어서 일반 string으로 수정했습니다.
- .env 파일은 노션에 공유해놓도록 하겠습니다.

.env로 token 변경

---

release/scripts/startup/abler/lib/tracker/__init__.py

버그가 있었습니다 흑흑 코드리뷰때 제대로 못보고 넘어갔네용
세 줄이 한 줄로 된건 black 이 돌아서입니다!

트래킹 관련 .env 수정사항

---

release/scripts/startup/abler/pref.py

파일 오픈 시 view transform을 자동으로 "Standard"로 바꿔주도록 기작을 추가해주었습니다.

open with view_transform "Standard"

---

release/datafiles/locale/po/ko.po

Object Control -> "오브젝트 설정" 으로 한글 번역 추가했습니당

translate Object Control

---

release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/lib/tracker/_tracker.py

tracker use_state

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/face_control.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/tracker/_tracker.py

bloom prop이 scene.eevee.use_bloom같이 기본 내장된 prop이라, 새로운 ACON_prop.bloom properties를 만들고 update 함수 안에 트래커를 심었습니다.

tracker bloom prop button

---

release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/tracker/_tracker.py

bloom 트래킹처럼 새로운 prop을 만들어주고 update 안에 트래커를 심어주었습니다!
Depth of Field와 Background Images 둘 다 Camera Control 패널 안에 있어서 하나의 브랜치에서 작업했습니다

tracker Depth of Field & Background Images

---

release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/shadow.py

type annotation을 본격적으로 적용하기에 앞서서 메인 말고 converter 브랜치에 한번 고쳐서 올려봤습니다.
내용을 내일 한번 보고 정책을 정해보면 좋을 것 같습니다.

타입 어노테이션 테스트를 위한 브랜치

---

release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/shadow.py

1. 메인 브랜치에도 타이핑을 추가했습니다.
2. use_bloom을 넣으면서 오타가 하나 나서 빌드에러가 있었는데, 어떻게 흘러들어갔는지는 모르지만 일단 고쳤습니당

메인 브랜치에 타이핑 추가 + 오타 수정

---

release/scripts/startup/abler/render_control.py

prev_scene_name에 렌더 이전의 scene 이름을 저장해서 렌더 후 다시 불러오게끔 수정했습니다.

get, set prev_scene_name

---

release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/lib/tracker/_get_ip.py
release/scripts/startup/abler/lib/tracker/_mixpanel.py
release/scripts/startup/abler/lib/tracker/_sentry.py
release/scripts/startup/abler/lib/tracker/_tracker.py

get_ip 함수에서 `try : ip = get("https://api.ipify.org").text`로 ip를 받아오고 _mixpanel.py의 _enqueue_email_update 함수에 ip를 meta데이터에 심어주면 믹스패널에서 자동으로 국가별 트래킹을 해줍니닷!

믹스패널 국가별 트래킹

---

launcher_abler/AblerLauncher.py
launcher_abler/lib.py
launcher_abler/privilege_helper.py
release/scripts/startup/bl_operators/wm.py

1. 파일 드래그앤드랍에 import 기능 심기
2. 윈도우에서 런쳐로 에이블러 실행시 블렌더를 관리자권한 없이 실행하도록 AblerLauncher.py 수정

drag-and-drop

---

release/scripts/startup/abler/render_control.py

prev_scene_name이랑 initial_scene.name이 같아서 이전에 쓰고있는 initial_scene.name을 재활용하는걸로 변경했습니다!

initial_scene 재활용

---

release/scripts/startup/abler/lib/shadow.py

acon_sun.type -> acon_sun.data.type으로 변경했습니당
빌드 후 잘 작동되는것까지 확인했습니다

햇빛 강도 오류 수정

---

release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/face_control.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/layer_control.py
release/scripts/startup/abler/object_control.py
release/scripts/startup/abler/render_control.py
release/scripts/startup/abler/scene_control.py

어제 검토 내용을 바탕으로 UNDO 옵션을 추가했습니다.

필요한 오퍼레이터에 UNDO 옵션 추가

---

release/scripts/startup/abler/lib/post_open.py

렌더시 태양 강도가 변경(v0.1.7)

---

release/scripts/startup/abler/__init__.py
release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/face_control.py
release/scripts/startup/abler/layer_control.py
release/scripts/startup/abler/object_control.py
release/scripts/startup/abler/render_control.py

코드 가끔 보다가 가독성 떨어지는 부분이 있는 것 같아서 지금 제 눈에 보이는 애들만 살짝 수정해봤습니다!

가독성 있도록 살짝 리팩토링

---

release/scripts/startup/abler/lib/async_task.py
release/scripts/startup/abler/lib/cameras.py
release/scripts/startup/abler/lib/config_env.py
release/scripts/startup/abler/lib/login.py
release/scripts/startup/abler/lib/materials/materials_handler.py
release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/lib/remember_username.py
release/scripts/startup/abler/lib/render.py
release/scripts/startup/abler/lib/scenes.py
release/scripts/startup/abler/lib/shadow.py

Type annotation을 진행중입니다.
금일 작업 기록용으로 남겨놓으니 아직 리뷰는 참아주세욧...!

Typing part 2

---

release/datafiles/locale/po/ko.po
release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/face_control.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/object_control.py

1차로 번역 누락된 녀석들만 추가했습니다.
2차로 마우스 오버시 기능명이 중복되거나 설명 바꿔야할 부분들 검토 후 작업하겠습니닷(리뷰는 아직 참아주세요)

마우스 오버시 기능 안내 추가

---

release/scripts/startup/abler/lib/tracker/_mixpanel.py
release/scripts/startup/abler/lib/tracker/_sentry.py
release/scripts/startup/abler/lib/tracker/_tracker.py

트래킹 관련 불필요한 로깅 제거

---

.gitmodules

io_skp 섭모듈이 main브랜치로 흘러들어가서 이를 삭제했습니다.

removed io_skp

---

release/datafiles/locale/po/ko.po
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/object_control.py
release/scripts/startup/abler/render_control.py
release/scripts/startup/abler/scene_control.py

기획세션 및 서나님과 논의 후 업데이트 했습니다!
(진짜진짜진짜최종..)

마우스 오버시 기능 안내 업데이트

---

release/datafiles/locale/po/ko.po

[Hotfix] 마우스오버 번역 누락 수정 - v0.1.8

---

release/datafiles/locale/po/ko.po

[Hotfix] 마우스오버 번역 누락 수정 
