ACON3D/ABLER

build_files/cmake/platform/platform_apple_xcode.cmake

현재 맥에서 컨버터 작업을 하려면 반드시 x86_64(인텔맥)용 빌드를 해야 하는데, 
해당 빌드 옵션(CMAKE_OSX_ARCHITECTURES)이 비활성화되어 있어서 `feature/converter-submodule` 브랜치에서는 다시 이 설정을 쓸 수 있도록 cmake 스크립트를 수정했었습니다.
이 내용을 main 브랜치에도 넣어야 할 필요가 있습니다. 맥에서 컨버터 작업과 에이블러 작업을 병행하려면 main 브랜치 역시 x86_64 빌드를 허용해 줄 필요가 있습니다.

allow CMAKE_OSX_ARCHITECTURES

---

release/datafiles/locale/po/ko.po
release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/object_control.py

This PR creates following changes to UI
1. Turning on `Use State` moves state slider to 1.0
2. Turning off `Use State` moves state slider to 0.0
3. Turning off `Use State` does not remove state data
4. `Update State` button moves state slider to 1.0, updates `end_state` instead of `mid_state`

Improve state UI

---

release/scripts/startup/abler/lib/tracker/_mixpanel.py

mixpanel에서 식별자가 달라도 username이 같은 경우 같은 active-user로 보도록 추가했습니다!

add alias tid to email

---

release/scripts/startup/abler/__init__.py
release/scripts/startup/abler/pref.py

백그라운드 옵션을 켜고 자동 컨버팅을 돌리는데, `bpy.data.screens`에 접근하는데 크래시가 계속 나서 --background 또는 -b 옵션이 켜져있을 경우에는  해당 데이터를 이용하지 않도록 수정했습니다.

백그라운드 옵션을 켜도 에러가 나지 않게 수정

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/camera_control.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py

general 패널에 있는 fly 버튼 tracker를 만들었습니다. camera control 패널에 있는 fly 버튼과 구분하기 위해 변수명을 "fly_in_general"로 설정했습니다.
원래는 general 패널에 row.operator("view3d.walk", text="Fly (shift + `)", text_ctxt="*")로 오퍼레이터가 바로 불러오도록 되어있어서 tracking할 수 있도록 class를 새로 만들었습니다!

tracking fly button in general

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/render_control.py

6개의 렌더 오퍼레이터에 tracker를 심어주었습니다.
Acon3dRenderAllOperator와 Acon3dRenderShadowOperator에선 내부에서 심어줄 부분이 없어서 def prepare_queue를 넣고 tracker를 심어준 뒤에 오버라이딩 하는 쪽으로 추가했습니다.
추가로 F12 버튼도 acon3d.render_quick 오퍼레이터로 변경해 트래킹이 가능토록 수정했습니다.

tracking all renders

---

release/scripts/presets/keyconfig/keymap_data/abler_default.py
release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/bl_ui/space_topbar.py

tracker를 심은채로 file open 오퍼레이터를 새로 만들어 우측 패널의 버튼과 단축키(ctrl+O)에서 트래킹이 되도록 설정했습니다.
오퍼레이터에 tracker를 심은 상태로는 윈도우 창에서 파일을 더블클릭 시 open 트래킹을 할수 없어, 에이블러 런처를 실행할 시 파일명을 확인하여 빈 문자열(런처로 실행시엔 파일명은 빈 문자열)이 아닐경우 open으로 간주하고 트래킹을 하도록 추가했습니다.

tracking file open

---

.gitignore

.env가 환경에 있을 확률이 높은데 빠르게 gitignore에 추가를 해야 노출이 안될 것 같아서 빠르게 머지 하겠습니다.

컨버터 브랜치에 .env gitignore 추가

---

release/scripts/startup/abler/lib/tracker/_mixpanel.py
release/scripts/startup/abler/lib/tracker/_sentry.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/lib/tracker/_versioning.py

- get_version 함수를 분리했습니다.
- track, _enqueue_event 함수에 properties 파라미터를 추가하고, 여기에 버전 정보가 기본으로 들어가도록 만들었습니다.

Mixpanel 이벤트에 버전 정보 넣기

---

release/scripts/startup/abler/layer_control.py

Create Group, Explode Group을 실행할 때 컬렉션을 생성하는 구조를 변경합니다.
* 기존: 문어발처럼 모든 그룹들이 병렬적으로 생성됩니다.
* 변경후: Parent-Child 구조를 유지하여 직렬 & 병렬 구조로 생성합니다.
Create Group했을 때의 outliner
Explode Group했을 때 outliner

add groups in tree structure

---

abler_requirements.txt
release/scripts/startup/abler/credential_modal.py
release/scripts/startup/abler/lib/login.py
release/scripts/startup/abler/lib/post_open.py

1. File Open과 Login Auto를 나누었습니다. 파일을 열때 기본 '코니방'이 뜨면 `bpy.data.filepath`에서 ""(빈 문자열)이 뜹니다. 요걸 이용해 File Open 버튼이나 파일을 더블클릭해서 열면 `bpy.data.filepath != ""`이 돼서 file open이라고 인식하고 tracker.file_open()을 실행합니다.
2. Login Auto가 맨 처음 에이블러를 실행했을때만 트래킹되고 창이 열려있는 상태에서 또 에이블러를 킨다면(주로 파일을 더블클릭해서 열때) Login Auto가 트래킹되지 않도록 했습니다. 에이블러를 실행했을 때 시스템 환경창(윈도우에선` subprocess.check_output(["tasklist"]),` 맥에선 `os.popen("ps -Af"))`에서 에이블러가 켜져있는지(윈도우에선 에이블러 실행 시 blender로 떠서 추가했습니다) 확인하고 이미 켜져있다면 Login Auto를 하지 않도록 기작했습니다.

separate file open & login auto

---

release/scripts/startup/abler/lib/__init__.py
release/scripts/startup/abler/lib/config_env.py
release/scripts/startup/abler/lib/tracker/__init__.py

.env를 ABLER폴더 최상단 루트폴더에 위치한 상태에서 load하기 위해 _walk_to_root와 find_dotenv 함수를 만들어 load_dotenv 하도록 변경했습니다.
또한 load_dotenv가 실행되는 config_env.py를 init에서 실행하도록 from . import config_env 구문을 추가해주었습니다.

separate load_dotenv

---

release/scripts/startup/abler/lib/tracker/_sentry.py

개발 버전의 에러를 Sentry 알림에서 제외하기 위해 필요한 내용입니다.
[Sentry 이슈 링크](https://sentry.io/organizations/carpenstreet/issues/2913262903/?project=6046815&query=is%3Aunresolved)
Fixes #36

Sentry 에 environment 설정 추가

---

release/scripts/startup/abler/general.py

Imported 콜렉션 하위에 layers.001이 생겨서 발생하는 문제라 이름만 수정하려다가 Layers콜렉션이 레이어 패널과 관련돼 있으므로 이중으로 있을 필요가 없어보여 Imported 콜렉션을 아예 삭제했습니다!
이미지와 같이 똑같은 파일을 import하면 겹치는 콜렉션 이름에 자동으로 숫자가 바뀌고 있습니다.

separate same-name collections

---

release/scripts/startup/abler/custom_properties.py

원래 스케치업에서는 각 오브젝트(그룹, 인스턴스)가 하나의 레이어에만 속할 수 있지만,
에이블러로 컨버팅을 할 때 계층 관계를 풀어헤쳐서 가져오기 때문에, 에이블러에서는 하나의 오브젝트가 여러 레이어(컬렉션)에 속할 수 있습니다.
이 때, 오브젝트가 속한 두 레이어(A, B라고 합시다) 중 A, B 를 모두 끄고 나서 A 를 켜면,
원래는 오브젝트가 보이지 않아야 정상입니다 (A, B 모두 켜져있어야 오브젝트가 보이는 것이 스케치업의 동작 방식)
하지만 현재 로직상 레이어 A를 켜면 레이어 A에 속한 모든 오브젝트를 켜버리기 때문에, 스케치업의 동작 방식과 달라지게 됩니다.
이를 "해당 오브젝트가 속한 모든 레이어가 켜져 있어야 오브젝트를 켠다"로 수정해서 스케치업과 같은 방식으로 동작하게 만들었습니다.
(다만 Layer0 관련해서는 다른 점이 있는데, 이건 오프라인에서 자세히 공유하겠습니다.)
Fixes #58

오브젝트가 속한 모든 레이어가 켜져야 오브젝트가 보여지도록 수정

---

release/scripts/startup/abler/lib/post_open.py

현재 change_and_reset_value에서 기본 씬인 "Scene"의 값을 변경해주고 있는데 
유저가 저장할 때 Scene을 삭제할 수 있어서 현재 씬인 context.scene의 값을 변경해주도록 수정했습니다.

change_and_reset_value의 scene을 현재 scene으로 변경

---

release/scripts/startup/abler/lib/post_open.py

현재 파일 오픈시 패널엔 강도가 1.0으로 되어있는데 실제론 2.0입니다.
강도의 default-value값을 2.0으로 변경했습니다.
(default-value 값을 바꾸는게 좋을지, 혹은 1.0으로 맞추되 실제론 2.0이 적용되는게 좋을지는 의견 부탁드립니다!)

렌더시 태양 강도가 변경

---

release/datafiles/locale/po/ko.po
release/scripts/startup/abler/custom_properties.py
release/scripts/startup/abler/lib/objects.py
release/scripts/startup/abler/object_control.py

드롭다운 박스에 active_object와 속한 모든 그룹들을 볼수 있게 해두었습니다. 아이콘을 추가해 오브젝트와 그룹을 분리시켰고, 아래로 갈수록 최상단입니다. 
그 옆엔 4개 operator 버튼을 두었고 코드상에선 빈 `execute(self, context): return`로 두어 요 안에 기능 추가하면 됩니닷
각각의 버튼에 국문 번역도 넣었습니다.

그룹네비게이션 UI

---

release/scripts/startup/abler/render_control.py

퀵렌더에서 선택 개체를 담는 initial_selected_objects 리스트가 다른 개체를 선택 후 퀵렌더를 실행하면 리스트에 이전 내용이 남겨져 오류가 나고 있었습니다. 그래서 퀵렌더 후 `initial_selected_objects.clear()`로 리스트를 비워주도록 추가했습니다.

퀵렌더시 선택 개체 외곽선 사라지기

---

release/scripts/startup/abler/render_control.py

현재 `Acon3dRenderTempSceneOperator`가 shadow 렌더와 동일해 temp 클래스는 필요한 내용만 넣고 shadow 렌더에 해당하는 녀석들은 따로 빼두었습니다. 또한 line 렌더와 snip 렌더에서 temp 클래스에서 받았던 내용들도 추가해주었습니다.

render control 리팩토링

---

abler_dev_build.py

`python abler_dev_build.py`로 파이썬 스크립트만 옮겨담아서 빌드를 적게 해도 되는 파일을 만들었습니당

abler_dev_build 파일 추가

---

release/scripts/startup/abler/lib/post_open.py
release/scripts/startup/abler/lib/tracker/_tracker.py
release/scripts/startup/abler/pref.py

`AconSceneProperty.__annotations__`로 AconSceneProperty의 변수들을 모두 가져와 getattrt, setattr을 써서 change_and_reset_value를 변경했습니다.
현재 AconSceneProperty에는 크게 FloatProperty, BoolProperty, StringProperty, EnumProperty가 있는데, 여기서 FloatProperty(+ int, 값이 2면 type이 int로 나와 or연산으로 추가)인 속성만 변경하도록 했습니다. BoolProperty는 기능을 켜고끄는 속성인데 요녀석들을 업데이트해주면 파일을 열때마다 믹스패널이 모든 기능에 트래킹 돼서 빼두었고, str으로 구분되는 StringProperty와 EnumProperty는 특정된 값만 받기때문에 그 값이 없으면 error가 나서 아예 빼두었습니다.
FloatProperty가 파라미터 값들이라 요녀석들만 받아도 될거 같은데 리뷰해주시고 코멘트 편하게 부탁드립니닷!

SceneProperty 모두 업데이트

---

release/scripts/startup/abler/lib/layers.py

- 그룹 내비게이션에서 UP을 실행할때 하나짜리 그룹 -그룹-오브젝트 의 형식에서 여러번 눌러야 제대로 작동하는 것 같이 보이는 현상을 피하기 위해서 all_object의 길이가 1보다 클 때 루프를 탈출하는 while 문을 사용했음
- 그런데 실제로 최상위그룹-그룹-오브젝트의 구조를 가지는 그룹이 존재했고, 이 때 무한루프가 나타나는 현상이 발생
- 최대 5회의 loop 반복으로 바꾸어서 중간에 조건에 부합하면 (all_objects의 길이가 1보다 큼) 루프를 탈출하게 만들어서 타협을 함.

그룹 내비게이션 무한루프 버그 픽스

---

release/scripts/startup/abler/lib/materials/materials_handler.py

Acon3dRenderTempSceneOperator 를 상속받는 렌더 오퍼레이터 실행 이후에 투명 재질이 빛 투과를 하지 못하게 되는 현상을 수정했습니다.
어떤 이유에서인지 toggle_shadow 에 걸려있는 update handler 가 제대로 작동되지 않는 것으로 보여서, 해당 update handler 에서 해 주는 업데이트를 직접 해주는 코드를 추가했습니다. 코드 중복이 발생해서 100% 마음에 들지는 않는 해결책이긴 합니다.

투명 재질이 temp scene 렌더 이후 빛을 투과시키지 못하는 문제 수정

---

release/scripts/startup/abler/credential_modal.py

어떤 작업이었는지는 슬랙으로 메시지 드리겠습니다!
패스워드 보여지고 있는 상태에 따라 패스워드 가져오는 속성을 다르게 해야하는 것을, password 만 보고 있어서 생긴 문제였습니다.
AsyncTask 도입 전에도 원래 잘 동작하던 기능인지는 확인해보지는 않았는데, 그 때 뭔가 꼬였을 수도 있겠다는 생각은 듭니다.
"패스워드 보여지게 만든 후, 두 번째 로그인 시도했을 때 성공하게 만든 코드"는 필요 없어 보여서 삭제했습니다.
스듴님은 바쁘시니 @Youdiie @habijung  리뷰 부탁드려요!

패스워드 보여지는 상태에서 첫 번째 로그인에 실패하는 문제 수정

---

release/datafiles/locale/po/ko.po
release/scripts/startup/abler/general.py
release/scripts/startup/abler/lib/tracker/_tracker.py

- `General` 패널 `File Open` 과 `Import` 아래에 `Save` / `Save As` 생성
- Mixpanel 트래킹을 위한 트래킹 기능 추가
추가로 더 필요한 부분 있으면 말씀해주세요!

General에 Save Operator 추가

---

release/scripts/startup/abler/lib/render.py

Full render 할 때 배경 이미지의 위치가 뷰포트와 다르게 변동하는 이슈입니다.
해당 기작은 Full render 버튼을 누를 때 compositor에 의해서 구현되도록 개발되어 있습니다. 이 때 compositor에서 배경이미지의 위치를 조정하는 transform 노드의 파라미터가 뷰포트의 배경이미지를 제대로 컨버팅하지 못하고 있었습니다.
또한 다음과 같은 특이사항이 있습니다. (렌더 해상도: resolution, 카메라 배경이미지 위치: offset)
* transform_x 값은 문제 없이 단순하게 컨버팅됨 (`transform_x = resolution_x * offset_x`)
* transform_y 값은 resolution_y 값과는 관계 없이 resolution_x 값에 따라 변동함
따라서 다음과 같은 보정계산식을 적용하였습니다.
```
transform_y = resolution_x * offset_y * 9 / 8
```
이 때의 마지막 보정 상수(`9 / 8`)는 실험적으로 추정한 근사값입니다.

fix compositor background image transform calculation

---

release/scripts/startup/abler/lib/tracker/_mixpanel.py

기존에는 최초 tid 생성 시에 파일을 쓰자마자 읽었었는데,
이 때 파일이 다 쓰여지기 전에 읽는 경우가 생기는 것으로 추정돼서,
파일 읽기를 먼저 시도하고 없으면 파일 쓰기만 시도함으로써
파일 쓰기 직후에 파일 읽기가 일어나는 일이 없도록 수정했습니다.
혹시나 파일 생성만 되고 쓰기에 실패한 경우,
uuid 포맷이 아닌 다른 포맷이 기록되어 있을 수 있으니
읽기 시점에 유효성 검증 과정을 추가했습니다.
tid 파일에 UUID 형식에 어긋나는 문자열이 들어있는 경우, tid 파일을 삭제하도록 수정했습니다.
기존에는 anonymous 를 tid 로 사용했는데, 이렇게 했을 때 다수 사용자의 데이터가 섞일 수 있다는 문제가 있습니다.
이보다는 아예 트래킹이 일시적으로 비활성화되는 것이 맞다고 판단돼서, 그렇게 수정했습니다.
distinct_id 가 비어있어서 이벤트를 전송하면 예외가 발생하는 상태에 빠졌을 때에도,
5초에 한 번씩 Mixpanel 에 flush 하는 과정을 중지하지 않아서 예외가 다수 발생했습니다.
Mixpanel flush 과정 중에서 예외가 발생하면, 더 이상 전송시도를 하지 않도록 처리했습니다.
---
그 밖에, 수정을 하면서 `Mixpanel 에 이벤트 전송을 할 수 없는 상황이 됐을 때, 반드시 Sentry 에 에러 리포팅이 되도록 reraise 를 한다` 는 기준으로 코드를 작성했습니다.

믹스패널 트래킹 부분에서 반복적으로 발생하고 있는 에러에 대한 처리 추가

---

release/scripts/startup/abler/camera_control.py

센트리 오류 중 cameraName = ""인 경우에는 bpy.data.objects[]에서 네이밍으로 찾을 수 없다고 오류가 생깁니다. 실제로 cameraName이 있는지 바다코끼리로 확인하도록 변경했습니다.
(노션 카드 : https://www.notion.so/acon3d/3D-My-Cards-eba53ab450d24d71804448ab0f277459?p=76a2bcd390e248d8a299e62e1c109a3e)

cameraName이 없을 때 에러

---

release/scripts/startup/abler/credential_modal.py

에이블러를 로그인 없이 사용 가능한 문제가 있었습니다.
오류 : `ord() expected a character, but string of length 0 found`
- `char2key(c)` 에서 키보드 값이 없을 때 `splash` 창 띄워주기
- 마우스 왼쪽, 중간, 오른쪽 모든 클릭에 대해서 `splash` 창 띄워주기
- `splash` 창이 없을 때 키보드를 연타해도 `splash` 창 생성

로그인 없이 사용하는 문제 해결
